function cfg = build_scenario_config()
%% Auto-generated by UAM Scenario Builder (web) — ajustado 2026-05-27
%% Base de parametros que estava funcionando + hotspots Interlagos + Risk-A*

%% ---- Arrival model ----------------------------------------
arrModel = 'deterministic';

%% ---- Core simulation parameters ---------------------------
cfg.schedulingPolicy = 'round-robin';
cfg.sched_alpha      = 0.5;

cfg.csvExport        = false;
cfg.csvDir           = 'csv_export';

cfg.numDrones       = 5;
cfg.corridorLength  = 30000;
cfg.updateRate      = 15;
cfg.speedVal        = 15;
cfg.flightTime      = cfg.corridorLength / cfg.speedVal;

cfg.fc              = 3.5e9;
cfg.pTransmitDrone  = 23;
cfg.gNB_Gain        = 15;
cfg.noiseFigure     = 7;
cfg.bw              = 20e6;
cfg.thermalNoise    = -174 + 10*log10(cfg.bw);
cfg.thresholdSNR    = 5;

cfg.r_min           = 10;
cfg.k_aoi           = 0.5;
cfg.dronesPerSlot   = 1;

cfg.droneEastPos    = 0;
cfg.minStartDelay   = 2;
cfg.maxStartDelay   = 450;

cfg.radioDelay      = 1;
cfg.coreDelay       = 2;
cfg.videoDelay      = 10;
cfg.latency_base    = cfg.radioDelay + cfg.coreDelay + cfg.videoDelay;

cfg.w_unc           = 0.33;
cfg.w_map           = 0.33;
cfg.w_vid           = 0.34;
cfg.v_max           = cfg.speedVal;

%% ---- Dual-source video model ------------------------------
cfg.videoModel      = 'atomic';
cfg.fps             = 30;
cfg.L_vid           = 10;
cfg.GOP             = 15;
cfg.L_I             = 30;
cfg.L_P             = 1;
cfg.L_c2            = 1;
cfg.w_coh           = 5;
cfg.L_nom           = 0.01;
cfg.p_c2            = 0.80;
cfg.p_vid           = 0.80;
cfg.rho_0           = 0.01;

%% ---- Base stations ----------------------------------------
cfg.microBSPos = [0  -20000  -30;
                  0       0  -30;
                  0   20000  -30];   % [East, North, Alt]

cfg.rng_seed        = 42;

%% ---- Hotspots Interlagos (coordenadas em metros do centro do corredor) --
cfg.numHotspots     = 0;            % suprime o hotspot aleatorio
cfg.manualHotspots = [
     28   24   0.10   90;
     56   28   0.10   90;
     76   46   0.10  130;
    102   50   0.10  210;
    137   57   0.10  210;
    181   72   0.10  210;
    297  376   0.10  210;
    261  415   0.10  210;
    281  402   0.10  210;
    186  455   0.10  210;
    107  488   0.10  210;
   -128  -49   0.10  210;
   -233  -71   0.10  210;
   -183  -68   0.10  210;
   -754  567   0.10  210;
   -686  530   0.10  210;
   -621  502   0.10  210;
   -587  481   0.10  210;
   -658  499   0.10  210;
   -695  518   0.10  210;
   -720  524   0.10  210;
];

%% ---- Routing (Risk-A* pre-flight path planning) -----------
cfg.routing.mode           = 'risk_astar';
cfg.routing.w_d            = 0.75;
cfg.routing.w_r            = 0.25;
cfg.routing.lambda         = 1e-4;
cfg.routing.uav_mass       = 1.5;
cfg.routing.uav_fall_speed = 20;
cfg.routing.I              = 100;
cfg.routing.I0             = 34;
cfg.routing.uav_sheltering = 0.5;

%% ---- Arrival model fields ----------------------------------
cfg.arrivalModel = arrModel;

switch arrModel
    case 'deterministic'
        cfg.det_spacing = (cfg.maxStartDelay - cfg.minStartDelay) / max(cfg.numDrones - 1, 1);
    otherwise
        % uniform — no extra params
end
end
