function cfg = build_scenario_config()
%% Auto-generated by UAM Scenario Builder (web)
%% 2026-03-18T09:15:25.065Z

cfg.schedulingPolicy = 'pf-classic';  % 'pf-classic' | 'round-robin' | 'pf-aoi' | 'risk-aware' | 'hybrid'
cfg.sched_alpha      = 0.5;            % hybrid only: weight between PF-AoI and Risk-Aware

cfg.numDrones       = 20;
cfg.corridorLength  = 1800;
cfg.flightTime      = 25;
cfg.updateRate      = 5;
cfg.dronesPerSlot   = 1;
cfg.droneEastPos    = 100;
cfg.minStartDelay   = 20;
cfg.maxStartDelay   = 50;

cfg.fc              = 3.5e9;
cfg.pTransmitDrone  = 23;
cfg.gNB_Gain        = 8;
cfg.noiseFigure     = 6;
cfg.bw              = 20e6;
cfg.thresholdSNR    = 10;

cfg.radioDelay      = 5;
cfg.coreDelay       = 10;
cfg.videoDelay      = 11;

cfg.w_unc           = 0.40;
cfg.w_map           = 0.40;
cfg.w_vid           = 0.20;
cfg.r_min           = 25;
cfg.k_aoi           = 1;
cfg.tau_max         = 500;
cfg.d_crit          = 150;
cfg.R_bar_sys       = 100000;

cfg.microBSPos = [
    -160  30  -30 ];
cfg.masterPos  = [-600  0  -40];

cfg.numHotspots     = 1;
cfg.rng_seed        = 42;

cfg.manualHotspots(1,:) = [-678 239 0.95 120];
cfg.manualHotspots(2,:) = [353 249 0.95 120];
end