function cfg = build_scenario_config()
%% Auto-generated by UAM Scenario Builder (web)
%% 2026-05-27T20:54:55.193Z

%% ---- Arrival model ----------------------------------------
arrModel = 'deterministic';

%% ---- Core simulation parameters ---------------------------
cfg.schedulingPolicy = 'max-weight-drift';


%% ---- Routes (fleet groups with individual entry/exit) -----------
% cfg.numDrones is auto-computed as sum([cfg.routes.numDrones]).
% Per-drone flight time = norm(goal - start) / cfg.speedVal.
cfg.routes(1).numDrones = 2;
cfg.routes(1).start     = [0  -3000];   % [North, East]
cfg.routes(1).goal      = [0  3000];   % [North, East]
cfg.routes(1).label     = 'Route 1';
cfg.routes(2).numDrones = 5;
cfg.routes(2).start     = [500  3000];   % [North, East]
cfg.routes(2).goal      = [200  -3000];   % [North, East]
cfg.routes(2).label     = 'Route 2';

cfg.numDrones       = 10;   % auto-computed by validate_uam_config
cfg.corridorLength  = 3000.0;   % first route length (for speed)
cfg.flightTime      = 600;
cfg.updateRate      = 7;
cfg.speedVal        = cfg.corridorLength / cfg.flightTime;

cfg.fc              = 3.5e9;
cfg.pTransmitDrone  = 23;
cfg.gNB_Gain        = 15;
cfg.noiseFigure     = 7;
cfg.bw              = 20e6;
cfg.thermalNoise    = -174 + 10*log10(cfg.bw);
cfg.thresholdSNR    = 5;

cfg.r_min           = 10;
cfg.k_aoi           = 0.5;
cfg.dronesPerSlot   = 40;

cfg.droneEastPos    = 0;   % legacy — overridden by cfg.routes
cfg.minStartDelay   = 2;
cfg.maxStartDelay   = 45;

cfg.radioDelay      = 1;
cfg.coreDelay       = 2;
cfg.videoDelay      = 10;
cfg.latency_base    = cfg.radioDelay + cfg.coreDelay + cfg.videoDelay;

cfg.w_unc           = 1.0000;
cfg.w_map           = 1.9000e-3;
cfg.w_vid           = 10.00;
cfg.v_max           = cfg.speedVal;
cfg.tau_max         = 500;
cfg.d_crit          = 200;

cfg.R_bar_sys       = 500;

cfg.microBSPos = [
    -160  -148  -30 ];
cfg.masterPos  = [0  0  -60];

cfg.rng_seed        = 55;
cfg.numHotspots     = 1;
cfg.manualHotspots(1,:) = [28 24 0.10 90];
cfg.manualHotspots(2,:) = [56 28 0.10 90];
cfg.manualHotspots(3,:) = [76 46 0.10 130];
cfg.manualHotspots(4,:) = [102 50 0.10 210];
cfg.manualHotspots(5,:) = [137 57 0.10 210];
cfg.manualHotspots(6,:) = [181 72 0.10 210];
cfg.manualHotspots(7,:) = [297 376 0.10 210];
cfg.manualHotspots(8,:) = [261 415 0.10 210];
cfg.manualHotspots(9,:) = [281 402 0.10 210];
cfg.manualHotspots(10,:) = [186 455 0.10 210];
cfg.manualHotspots(11,:) = [107 488 0.10 210];
cfg.manualHotspots(12,:) = [-128 -49 0.10 210];
cfg.manualHotspots(13,:) = [-233 -71 0.10 210];
cfg.manualHotspots(14,:) = [-183 -68 0.10 210];
cfg.manualHotspots(15,:) = [-754 567 0.10 210];
cfg.manualHotspots(16,:) = [-686 530 0.10 210];
cfg.manualHotspots(17,:) = [-621 502 0.10 210];
cfg.manualHotspots(18,:) = [-587 481 0.10 210];
cfg.manualHotspots(19,:) = [-658 499 0.10 210];
cfg.manualHotspots(20,:) = [-695 518 0.10 210];
cfg.manualHotspots(21,:) = [-720 524 0.10 210];

%% ---- Routing (Risk-A* pre-flight path planning) -----------
cfg.routing.mode           = 'static';%'risk_astar';
cfg.routing.w_d            = 0.50;
cfg.routing.w_r            = 0.50;
cfg.routing.lambda         = 0.0001;
cfg.routing.uav_mass       = 1.5;
cfg.routing.uav_fall_speed = 20;
cfg.routing.I              = 100;
cfg.routing.I0             = 34;
cfg.routing.uav_sheltering = 0.5;

%% ---- Arrival model fields ----------------------------------
cfg.arrivalModel = arrModel;

switch arrModel

    case 'deterministic'
        cfg.det_spacing = (cfg.maxStartDelay - cfg.minStartDelay) / max(cfg.numDrones - 1, 1);
end
end