    function cfg = build_scenario_config()
%% Auto-generated by UAM Scenario Builder (web)
%% 2026-04-10T15:37:54.843Z

%% ---- Arrival model ----------------------------------------
arrModel = 'deterministic';

%% ---- Core simulation parameters ---------------------------

cfg.schedulingPolicy = 'round-robin';
cfg.sched_alpha      = 0.5;

cfg.csvExport        = false;
cfg.csvDir           = 'csv_export';

%% ---- Routes (fleet groups with individual entry/exit) ----------------
% cfg.numDrones is auto-computed as sum([cfg.routes.numDrones]).
% Per-drone flight time = norm(goal - start) / cfg.speedVal.

cfg.routes(1).numDrones = 3;
cfg.routes(1).start     = [-15000   0];   % [North, East] entry
cfg.routes(1).goal      = [ 15000   0];   % [North, East] exit
cfg.routes(1).label     = 'Route 1';

cfg.routes(2).numDrones = 2;
cfg.routes(2).start     = [-15000 -200];
cfg.routes(2).goal      = [ 15000  200];
cfg.routes(2).label     = 'Route 2';

% Reference speed and corridor length (first route)
cfg.corridorLength  = norm(cfg.routes(1).goal - cfg.routes(1).start);
cfg.updateRate      = 15;
cfg.speedVal        = 15;
cfg.flightTime      = cfg.corridorLength / cfg.speedVal;


cfg.fc              = 3.5e9;
cfg.pTransmitDrone  = 23;
cfg.gNB_Gain        = 15;
cfg.noiseFigure     = 7;
cfg.bw              = 20e6;
cfg.thermalNoise    = -174 + 10*log10(cfg.bw);
cfg.thresholdSNR    = 5;

cfg.r_min           = 10;
cfg.k_aoi           = 0.5;
cfg.dronesPerSlot   = 1;

cfg.droneEastPos    = 0;   % legacy — overridden by cfg.routes
cfg.minStartDelay   = 2;
cfg.maxStartDelay   = 450;

cfg.radioDelay      = 1;
cfg.coreDelay       = 2;
cfg.videoDelay      = 10;
cfg.latency_base    = cfg.radioDelay + cfg.coreDelay + cfg.videoDelay;

cfg.w_unc           = 0.33;
cfg.w_map           = 0.33;
cfg.w_vid           = 0.34;
cfg.v_max           = cfg.speedVal;

%% ---- Dual-source video model ------------------------------
%
%   cfg.videoModel selects the video-traffic regime:
%     'atomic' — draft Sec. II-D premise: every frame is a single
%                uniform atomic update of size L_vid = 1 packet,
%                generated at rate fps. Intra-GOP structure is
%                abstracted away. This is the regime that matches
%                the coherence-window risk R_vid (eq. 17) and the
%                one used in the INFOCOM submission.
%     'gop'    — legacy I/P-frame surrogate retained for extended
%                experiments only.
%
cfg.videoModel      = 'atomic';
cfg.fps             = 30;
cfg.L_vid           = 10;    % atomic-frame size (atomic mode)
cfg.GOP             = 15;   % kept for 'gop' mode
cfg.L_I             = 30;   % kept for 'gop' mode
cfg.L_P             = 1;    % kept for 'gop' mode
cfg.L_c2            = 1;
cfg.w_coh           = 5;
cfg.L_nom           = 0.01;
cfg.p_c2            = 0.80;
cfg.p_vid           = 0.80;
cfg.rho_0           = 0.01;

% BS position at 1/3 of corridor length
cfg.microBSPos = [0  -20000  -30;
    0  -0  -30;
     0  20000  -30;];  % [East, North, Alt]

cfg.rng_seed        = 42;
cfg.numHotspots     = 1;
cfg.manualHotspots  = [];

%% ---- Routing (Risk-A* pre-flight path planning) -----------
%  mode = 'static'     : drones follow a straight corridor (default)
%  mode = 'risk_astar' : Risk-A* computes minimum-cost paths pre-flight
%
cfg.routing.mode           = 'static';   % change to 'risk_astar' to enable
cfg.routing.w_d            = 0.5;        % distance weight  (w_d + w_r = 1)
cfg.routing.w_r            = 0.5;        % risk weight
cfg.routing.lambda         = 1e-4;       % drone-fall probability per flight
cfg.routing.uav_mass       = 1.5;        % kg
cfg.routing.uav_fall_speed = 20;         % m/s impact speed
cfg.routing.I              = 100;        % J — energy at 50% fatality
cfg.routing.I0             = 34;         % J — energy at 0%  fatality
cfg.routing.uav_sheltering = 0.5;        % sheltering fraction Sh_c (scalar default)

%% ---- Arrival model fields ----------------------------------
cfg.arrivalModel = arrModel;

switch arrModel

    otherwise
        % uniform — no extra params
end
end