function cfg = build_scenario_config()
%% Auto-generated by UAM Scenario Builder (web)
%% 2026-05-27T20:54:55.193Z

%% ---- Arrival model ----------------------------------------
arrModel = 'deterministic';

%% ---- Core simulation parameters ---------------------------
cfg.schedulingPolicy = 'pf-classic';

cfg.sched_alpha      = 0.5;
cfg.csvExport        = false;
cfg.csvDir           = 'csv_export';

%% ---- Routes (fleet groups with individual entry/exit) ----------------
% cfg.numDrones is auto-computed as sum([cfg.routes.numDrones]).
% Per-drone flight time = norm(goal - start) / cfg.speedVal.
cfg.routes(1).numDrones = 5;
cfg.routes(1).start     = [0  -3000];   % [North, East]
cfg.routes(1).goal      = [0   3000];   % [North, East]
cfg.routes(1).label     = 'Route 1';

cfg.routes(2).numDrones = 5;
cfg.routes(2).start     = [ 500  3000];   % [North, East]
cfg.routes(2).goal      = [ 200 -3000];   % [North, East]
cfg.routes(2).label     = 'Route 2';

% Reference speed and corridor length (first route)
cfg.corridorLength  = norm(cfg.routes(1).goal - cfg.routes(1).start);
cfg.updateRate      = 7;
cfg.speedVal        = 5;
cfg.flightTime      = cfg.corridorLength / cfg.speedVal;

cfg.fc              = 3.5e9;
cfg.pTransmitDrone  = 23;
cfg.gNB_Gain        = 15;
cfg.noiseFigure     = 7;
cfg.bw              = 20e6;
cfg.thermalNoise    = -174 + 10*log10(cfg.bw);
cfg.thresholdSNR    = 5;

cfg.r_min           = 10;
cfg.k_aoi           = 0.5;
cfg.dronesPerSlot   = 1;

cfg.droneEastPos    = 0;   % legacy — overridden by cfg.routes
cfg.minStartDelay   = 2;
cfg.maxStartDelay   = 45;

cfg.radioDelay      = 1;
cfg.coreDelay       = 2;
cfg.videoDelay      = 10;
cfg.latency_base    = cfg.radioDelay + cfg.coreDelay + cfg.videoDelay;

cfg.w_unc           = 1.0000;
cfg.w_map           = 1.9000e-3;
cfg.w_vid           = 10.00;
cfg.v_max           = cfg.speedVal;
cfg.tau_max         = 500;
cfg.d_crit          = 200;
cfg.R_bar_sys       = 500;

%% ---- Dual-source video model ------------------------------
cfg.videoModel      = 'atomic';
cfg.fps             = 30;
cfg.L_vid           = 10;
cfg.GOP             = 15;
cfg.L_I             = 30;
cfg.L_P             = 1;
cfg.L_c2            = 1;
cfg.w_coh           = 5;
cfg.L_nom           = 0.01;
cfg.p_c2            = 0.80;
cfg.p_vid           = 0.80;
cfg.rho_0           = 0.01;

%% ---- Base stations ----------------------------------------
cfg.microBSPos = [-160  -148  -30];   % [East, North, Alt]

%% ---- Ground risk hotspots ---------------------------------
cfg.rng_seed        = 55;
cfg.numHotspots     = 1;
cfg.manualHotspots  = [
     28   24  0.10   90;
     56   28  0.10   90;
     76   46  0.10  130;
    102   50  0.10  210;
    137   57  0.10  210;
    181   72  0.10  210;
    297  376  0.10  210;
    261  415  0.10  210;
    281  402  0.10  210;
    186  455  0.10  210;
    107  488  0.10  210;
   -128  -49  0.10  210;
   -233  -71  0.10  210;
   -183  -68  0.10  210;
   -754  567  0.10  210;
   -686  530  0.10  210;
   -621  502  0.10  210;
   -587  481  0.10  210;
   -658  499  0.10  210;
   -695  518  0.10  210;
   -720  524  0.10  210;
];

%% ---- Routing (Risk-A* pre-flight path planning) -----------
cfg.routing.mode           = 'risk_astar';
cfg.routing.w_d            = 0.50;
cfg.routing.w_r            = 0.50;
cfg.routing.lambda         = 0.0001;
cfg.routing.uav_mass       = 1.5;
cfg.routing.uav_fall_speed = 20;
cfg.routing.I              = 100;
cfg.routing.I0             = 34;
cfg.routing.uav_sheltering = 0.5;

%% ---- Arrival model fields ----------------------------------
cfg.arrivalModel = arrModel;

switch arrModel
    case 'deterministic'
        cfg.det_spacing = (cfg.maxStartDelay - cfg.minStartDelay) / ...
                          max(sum([cfg.routes.numDrones]) - 1, 1);
end
end
