function cfg = build_scenario_assimetrico()

%% Auto-generated by UAM Scenario Builder (web)
%% 2026-06-14T20:35:08.144Z

%% ---- Arrival model ----------------------------------------
arrModel = 'uniform';

%% ---- Core simulation parameters ---------------------------
cfg.schedulingPolicy = 'round-robin';


%% ---- Routes (fleet groups with individual entry/exit) -----------
% cfg.numDrones is auto-computed as sum([cfg.routes.numDrones]).
% Per-drone flight time = norm(goal - start) / cfg.speedVal.
cfg.routes(1).numDrones = 10;
cfg.routes(1).start     = [200      0];   % [North, East]
cfg.routes(1).goal      = [500  15000];   % [North, East]
cfg.routes(1).label     = 'Route 2';
cfg.routes(2).numDrones = 10;
cfg.routes(2).start     = [-500  15000];   % [North, East]
cfg.routes(2).goal      = [-600      0];   % [North, East]
cfg.routes(2).label     = 'Route 3';

cfg.numDrones       = 20;   % auto-computed by validate_uam_config
cfg.corridorLength  = 15003.0;   % norm([300, 15000]) — corredor 15 km
cfg.flightTime      = 1500;
cfg.updateRate      = 7;
cfg.speedVal        = cfg.corridorLength / cfg.flightTime;

cfg.fc              = 3.5e9;
cfg.pTransmitDrone  = 23;
cfg.gNB_Gain        = 15;
cfg.noiseFigure     = 7;
cfg.bw              = 20e6;
cfg.thermalNoise    = -174 + 10*log10(cfg.bw);
cfg.thresholdSNR    = 5;

cfg.r_min           = 10;
cfg.k_aoi           = 0.5;
cfg.dronesPerSlot   = 1;

cfg.droneEastPos    = 0;   % legacy — overridden by cfg.routes
cfg.minStartDelay   = 2;
cfg.maxStartDelay   = 45;

cfg.radioDelay      = 1;
cfg.coreDelay       = 2;
cfg.videoDelay      = 10;
cfg.latency_base    = cfg.radioDelay + cfg.coreDelay + cfg.videoDelay;

cfg.w_unc           = 1.0000;
cfg.w_map           = 1.9000e-3;
cfg.w_vid           = 10.00;
cfg.v_max           = cfg.speedVal;
cfg.tau_max         = 500;
cfg.d_crit          = 200;

cfg.R_bar_sys       = 500;

cfg.microBSPos = [
    5000  0  -30 ];   % [East, North, Alt(neg=above ground)] — 1/3 do corredor, 30 m altitude

cfg.rng_seed        = 55;
cfg.numHotspots     = 1;
% Hotspots na extremidade oposta à BS (East ≈ 12800–13200 m)
cfg.manualHotspots(1,:)  = [-716 13161 0.75 120];
cfg.manualHotspots(2,:)  = [-720 13143 0.75 120];
cfg.manualHotspots(3,:)  = [-702 13073 0.75 120];
cfg.manualHotspots(4,:)  = [-713 13047 0.75 120];
cfg.manualHotspots(5,:)  = [-716 13007 0.75 120];
cfg.manualHotspots(6,:)  = [-702 12951 0.75 120];
cfg.manualHotspots(7,:)  = [-698 12896 0.75 120];
cfg.manualHotspots(8,:)  = [-691 12863 0.75 120];
cfg.manualHotspots(9,:)  = [-676 12856 0.75 120];
cfg.manualHotspots(10,:) = [-676 12852 0.75 120];
cfg.manualHotspots(11,:) = [-676 12852 0.75 120];
cfg.manualHotspots(12,:) = [-676 12852 0.75 120];
cfg.manualHotspots(13,:) = [-738 12830 0.75 120];
cfg.manualHotspots(14,:) = [-783 12823 0.75 120];

%% ---- Routing (Risk-A* pre-flight path planning) -----------
cfg.routing.mode           = 'static';
cfg.routing.w_d            = 0.50;
cfg.routing.w_r            = 0.50;
cfg.routing.lambda         = 0.0001;
cfg.routing.uav_mass       = 1.5;
cfg.routing.uav_fall_speed = 20;
cfg.routing.I              = 100;
cfg.routing.I0             = 34;
cfg.routing.uav_sheltering = 0.5;

%% ---- Arrival model fields ----------------------------------
cfg.arrivalModel = arrModel;

switch arrModel

    otherwise
        % uniform — no extra params
end
end
