function cfg = build_scenario_assimetrico()

%% Auto-generated by UAM Scenario Builder (web)
%% 2026-06-14T20:35:08.144Z

%% ---- Arrival model ----------------------------------------
arrModel = 'uniform';

%% ---- Core simulation parameters ---------------------------
cfg.schedulingPolicy = 'round-robin';


%% ---- Routes (fleet groups with individual entry/exit) -----------
% cfg.numDrones is auto-computed as sum([cfg.routes.numDrones]).
% Per-drone flight time = norm(goal - start) / cfg.speedVal.
cfg.routes(1).numDrones = 10;
cfg.routes(1).start     = [200  -3000];   % [North, East]
cfg.routes(1).goal      = [500  3000];   % [North, East]
cfg.routes(1).label     = 'Route 2';
cfg.routes(2).numDrones = 10;
cfg.routes(2).start     = [-500  3000];   % [North, East]
cfg.routes(2).goal      = [-600  -3000];   % [North, East]
cfg.routes(2).label     = 'Route 3';

cfg.numDrones       = 20;   % auto-computed by validate_uam_config
cfg.corridorLength  = 6007.5;   % first route length (for speed)
cfg.flightTime      = 600;
cfg.updateRate      = 7;
cfg.speedVal        = cfg.corridorLength / cfg.flightTime;

cfg.fc              = 3.5e9;
cfg.pTransmitDrone  = 23;
cfg.gNB_Gain        = 15;
cfg.noiseFigure     = 7;
cfg.bw              = 20e6;
cfg.thermalNoise    = -174 + 10*log10(cfg.bw);
cfg.thresholdSNR    = 5;

cfg.r_min           = 10;
cfg.k_aoi           = 0.5;
cfg.dronesPerSlot   = 1;

cfg.droneEastPos    = 0;   % legacy — overridden by cfg.routes
cfg.minStartDelay   = 2;
cfg.maxStartDelay   = 45;

cfg.radioDelay      = 1;
cfg.coreDelay       = 2;
cfg.videoDelay      = 10;
cfg.latency_base    = cfg.radioDelay + cfg.coreDelay + cfg.videoDelay;

cfg.w_unc           = 1.0000;
cfg.w_map           = 1.9000e-3;
cfg.w_vid           = 10.00;
cfg.v_max           = cfg.speedVal;
cfg.tau_max         = 500;
cfg.d_crit          = 200;

cfg.R_bar_sys       = 500;

cfg.microBSPos = [
    2300  0  30 ];   % [East, North, Down]  — próxima ao cluster de hotspots


cfg.rng_seed        = 55;
cfg.numHotspots     = 1;
cfg.manualHotspots(1,:) = [-716 -1039 0.75 120];
cfg.manualHotspots(2,:) = [-720 -1057 0.75 120];
cfg.manualHotspots(3,:) = [-702 -1127 0.75 120];
cfg.manualHotspots(4,:) = [-713 -1153 0.75 120];
cfg.manualHotspots(5,:) = [-716 -1193 0.75 120];
cfg.manualHotspots(6,:) = [-702 -1249 0.75 120];
cfg.manualHotspots(7,:) = [-698 -1304 0.75 120];
cfg.manualHotspots(8,:) = [-691 -1337 0.75 120];
cfg.manualHotspots(9,:) = [-676 -1344 0.75 120];
cfg.manualHotspots(10,:) = [-676 -1348 0.75 120];
cfg.manualHotspots(11,:) = [-676 -1348 0.75 120];
cfg.manualHotspots(12,:) = [-676 -1348 0.75 120];
cfg.manualHotspots(13,:) = [-738 -1370 0.75 120];
cfg.manualHotspots(14,:) = [-783 -1377 0.75 120];

%% ---- Routing (Risk-A* pre-flight path planning) -----------
cfg.routing.mode           = 'static';
cfg.routing.w_d            = 0.50;
cfg.routing.w_r            = 0.50;
cfg.routing.lambda         = 0.0001;
cfg.routing.uav_mass       = 1.5;
cfg.routing.uav_fall_speed = 20;
cfg.routing.I              = 100;
cfg.routing.I0             = 34;
cfg.routing.uav_sheltering = 0.5;

%% ---- Arrival model fields ----------------------------------
cfg.arrivalModel = arrModel;

switch arrModel

    otherwise
        % uniform — no extra params
end
end